const data = [
    {
        prenom: "GABRIEL",
        annee_naissance: 2016,
        sexe: "M",
        nombre_occurences: 5877,
    },
    {
        prenom: "RAPHAEL",
        annee_naissance: 2016,
        sexe: "M",
        nombre_occurences: 5060,
    },
    {
        prenom: "JULES",
        annee_naissance: 2016,
        sexe: "M",
        nombre_occurences: 5033,
    },
    {
        prenom: "EMMA",
        annee_naissance: 2016,
        sexe: "F",
        nombre_occurences: 4723,
    },
    {
        prenom: "ADAM",
        annee_naissance: 2016,
        sexe: "M",
        nombre_occurences: 4655,
    },
    {
        prenom: "LEO",
        annee_naissance: 2016,
        sexe: "M",
        nombre_occurences: 4601,
    },
    {
        prenom: "LUCAS",
        annee_naissance: 2016,
        sexe: "M",
        nombre_occurences: 4587,
    },
    {
        prenom: "LOUIS",
        annee_naissance: 2016,
        sexe: "M",
        nombre_occurences: 4571,
    },
    {
        prenom: "LOUISE",
        annee_naissance: 2016,
        sexe: "F",
        nombre_occurences: 4174,
    },
    {
        prenom: "JADE",
        annee_naissance: 2016,
        sexe: "F",
        nombre_occurences: 4146,
    },
    {
        prenom: "ETHAN",
        annee_naissance: 2016,
        sexe: "M",
        nombre_occurences: 4101,
    },
    {
        prenom: "HUGO",
        annee_naissance: 2016,
        sexe: "M",
        nombre_occurences: 4057,
    },
    {
        prenom: "LIAM",
        annee_naissance: 2016,
        sexe: "M",
        nombre_occurences: 3664,
    },
    {
        prenom: "ALICE",
        annee_naissance: 2016,
        sexe: "F",
        nombre_occurences: 3484,
    },
    {
        prenom: "LEA",
        annee_naissance: 2016,
        sexe: "F",
        nombre_occurences: 3470,
    },
    {
        prenom: "INES",
        annee_naissance: 2016,
        sexe: "F",
        nombre_occurences: 3408,
    },
    {
        prenom: "MILA",
        annee_naissance: 2016,
        sexe: "F",
        nombre_occurences: 3251,
    },
    {
        prenom: "LENA",
        annee_naissance: 2016,
        sexe: "F",
        nombre_occurences: 3180,
    },
    {
        prenom: "LINA",
        annee_naissance: 2016,
        sexe: "F",
        nombre_occurences: 3112,
    },
    {
        prenom: "MANON",
        annee_naissance: 2016,
        sexe: "F",
        nombre_occurences: 3027,
    },
    {
        prenom: "ENZO",
        annee_naissance: 2006,
        sexe: "M",
        nombre_occurences: 8325,
    },
    {
        prenom: "LUCAS",
        annee_naissance: 2006,
        sexe: "M",
        nombre_occurences: 7189,
    },
    {
        prenom: "EMMA",
        annee_naissance: 2006,
        sexe: "F",
        nombre_occurences: 7090,
    },
    {
        prenom: "LEA",
        annee_naissance: 2006,
        sexe: "F",
        nombre_occurences: 6499,
    },
    {
        prenom: "MATHIS",
        annee_naissance: 2006,
        sexe: "M",
        nombre_occurences: 6173,
    },
    {
        prenom: "NATHAN",
        annee_naissance: 2006,
        sexe: "M",
        nombre_occurences: 6043,
    },
    {
        prenom: "MANON",
        annee_naissance: 2006,
        sexe: "F",
        nombre_occurences: 5568,
    },
    {
        prenom: "THOMAS",
        annee_naissance: 2006,
        sexe: "M",
        nombre_occurences: 5303,
    },
    {
        prenom: "HUGO",
        annee_naissance: 2006,
        sexe: "M",
        nombre_occurences: 5101,
    },
    {
        prenom: "CAMILLE",
        annee_naissance: 2006,
        sexe: "F",
        nombre_occurences: 5017,
    },
    {
        prenom: "THEO",
        annee_naissance: 2006,
        sexe: "M",
        nombre_occurences: 4963,
    },
    {
        prenom: "INES",
        annee_naissance: 2006,
        sexe: "F",
        nombre_occurences: 4823,
    },
    {
        prenom: "SARAH",
        annee_naissance: 2006,
        sexe: "F",
        nombre_occurences: 4580,
    },
    {
        prenom: "TOM",
        annee_naissance: 2006,
        sexe: "M",
        nombre_occurences: 4499,
    },
    {
        prenom: "JADE",
        annee_naissance: 2006,
        sexe: "F",
        nombre_occurences: 4490,
    },
    {
        prenom: "RAPHAEL",
        annee_naissance: 2006,
        sexe: "M",
        nombre_occurences: 4434,
    },
    {
        prenom: "LOUIS",
        annee_naissance: 2006,
        sexe: "M",
        nombre_occurences: 4395,
    },
    {
        prenom: "LOLA",
        annee_naissance: 2006,
        sexe: "F",
        nombre_occurences: 4053,
    },
    {
        prenom: "ANAIS",
        annee_naissance: 2006,
        sexe: "F",
        nombre_occurences: 3764,
    },
    {
        prenom: "LUCIE",
        annee_naissance: 2006,
        sexe: "F",
        nombre_occurences: 3640,
    },
    {
        prenom: "THOMAS",
        annee_naissance: 1996,
        sexe: "M",
        nombre_occurences: 9382,
    },
    {
        prenom: "ALEXANDRE",
        annee_naissance: 1996,
        sexe: "M",
        nombre_occurences: 8867,
    },
    {
        prenom: "NICOLAS",
        annee_naissance: 1996,
        sexe: "M",
        nombre_occurences: 8843,
    },
    {
        prenom: "MAXIME",
        annee_naissance: 1996,
        sexe: "M",
        nombre_occurences: 7766,
    },
    {
        prenom: "MANON",
        annee_naissance: 1996,
        sexe: "F",
        nombre_occurences: 7610,
    },
    {
        prenom: "LAURA",
        annee_naissance: 1996,
        sexe: "F",
        nombre_occurences: 7422,
    },
    {
        prenom: "MARIE",
        annee_naissance: 1996,
        sexe: "F",
        nombre_occurences: 7416,
    },
    {
        prenom: "CAMILLE",
        annee_naissance: 1996,
        sexe: "F",
        nombre_occurences: 7231,
    },
    {
        prenom: "KEVIN",
        annee_naissance: 1996,
        sexe: "M",
        nombre_occurences: 7001,
    },
    {
        prenom: "DYLAN",
        annee_naissance: 1996,
        sexe: "M",
        nombre_occurences: 6908,
    },
    {
        prenom: "QUENTIN",
        annee_naissance: 1996,
        sexe: "M",
        nombre_occurences: 6761,
    },
    {
        prenom: "ANTOINE",
        annee_naissance: 1996,
        sexe: "M",
        nombre_occurences: 6742,
    },
    {
        prenom: "JULIEN",
        annee_naissance: 1996,
        sexe: "M",
        nombre_occurences: 6258,
    },
    {
        prenom: "MARINE",
        annee_naissance: 1996,
        sexe: "F",
        nombre_occurences: 6222,
    },
    {
        prenom: "LEA",
        annee_naissance: 1996,
        sexe: "F",
        nombre_occurences: 6152,
    },
    {
        prenom: "FLORIAN",
        annee_naissance: 1996,
        sexe: "M",
        nombre_occurences: 6033,
    },
    {
        prenom: "PAULINE",
        annee_naissance: 1996,
        sexe: "F",
        nombre_occurences: 5959,
    },
    {
        prenom: "SARAH",
        annee_naissance: 1996,
        sexe: "F",
        nombre_occurences: 5464,
    },
    {
        prenom: "JULIE",
        annee_naissance: 1996,
        sexe: "F",
        nombre_occurences: 5329,
    },
    {
        prenom: "MATHILDE",
        annee_naissance: 1996,
        sexe: "F",
        nombre_occurences: 5122,
    },
];
