name: Déploiement

run-name: Déploiement initié par ${{ github.actor }}

on: [workflow_dispatch]

jobs:
  deploiement:
    runs-on: ubuntu-latest
    steps:
      - name: Clone dépôt
        uses: actions/checkout@v4

      - name: Set github user
        run: git config --global user.email "test@example.com" && git config --global user.name "CI/CD"

      - name: Autorise le compte sur le serveur de production
        run: echo "${{secrets.SSH_KEY}}" > ~/deploy_key && chmod 400 ~/deploy_key

      - name: Déplace les fichiers
        run: rsync -Pavz -e "ssh -i ~/deploy_key -o StrictHostKeyChecking=no" ./ ${{ secrets.USER }}@${{ secrets.SERVER }}:~/www