services:
  php:
    container_name: sae_203_dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./code:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    ports:
      - 80:80
    networks:
      - sae_203_network
    command: >
      sh -c "
        apache2-foreground & 
        until curl -s http://localhost > /dev/null; do
          sleep 1;
        done;
        echo '✅ Server ready on http://localhost';
        wait
      "
  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: sae_203-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - 3308:3306
    volumes:
      - ./code/base-de-donnees.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - sae_203_network
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    container_name: sae_203-phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sae_203_db
      MYSQL_USER: root
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    networks:
      - sae_203_network
  mailer:
    image: axllent/mailpit
    container_name: sae_203-mailpit
    ports:
      - 1026:1025
      - 8026:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MAILPIT_RELAY: 127.0.0.1:25
    networks:
      - sae_203_network

networks:
  sae_203_network:
    driver: bridge