services:
  app:
    container_name: sae_501_dev
    build:
      context: .
      target: dev
    ports:
      - "${PORT}:${PORT}"
      - "5173:5173"
      - "24678:24678"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      CHOKIDAR_USEPOLLING: true
      NODE_ENV: development
