services:
  app:
    container_name: sae_501_dev
    build: .
    ports:
      - "${PORT}:${PORT}"
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
