#!/bin/sh

if [ -e output.tmp.txt ]; then
    rm output.tmp.txt
else
    echo "----- pre-commit -----"

    # cd "$(git rev-parse --show-toplevel)" || exit 1

    if ! command -v python &> /dev/null; then
        # For linux/macos env
        python3 generation-archives/zip-ressources.proxy.py
    else
        python generation-archives/zip-ressources.proxy.py
    fi
fi

exit
