name: Bump version
run-name: ${{ github.actor }} is bumping version
on:
  workflow_dispatch:
jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
            node-version: 22.11.0
      - name: Set github user
        run: git config user.email "test@example.com" && git config user.name "CI/CD - MMI"
      - run: npm ci
      - run: npx release-it --ci
